/**
 * Re-exported Cursor SDK types.
 *
 * `effect-cursor-sdk` deliberately does not rebuild the public data model from
 * `@cursor/sdk`. The upstream SDK remains the source of truth for agent
 * options, run handles, message events, artifacts, MCP definitions, model
 * records, and platform helpers.
 *
 * @module
 */
export type {
  AgentDefinition,
  AgentMessage,
  AgentModeOption,
  AgentOperationOptions,
  AgentOptions,
  AgentUsage,
  CloudSendOptions,
  CursorRequestOptions,
  GetAgentMessagesOptions,
  GetAgentOptions,
  GetRunOptions,
  GetUsageOptions,
  ListAgentsOptions,
  ListResult,
  ListRunsOptions,
  LocalSendOptions,
  McpServerConfig,
  ModelListItem,
  ModelParameterDefinition,
  ModelParameterValue,
  ModelSelection,
  ModelVariant,
  Run,
  RunOperation,
  RunResult,
  RunResultStatus,
  RunStatus,
  RunUsage,
  SDKAgent,
  SDKAgentInfo,
  SDKArtifact,
  SDKAssistantMessage,
  SDKImage,
  SDKImageDimension,
  SDKMessage,
  SDKModel,
  SDKRepository,
  SDKStatusMessage,
  SDKSystemMessage,
  SDKTaskMessage,
  SDKThinkingMessage,
  SDKToolUseMessage,
  SDKUsageMessage,
  SDKUser,
  SDKUserMessage,
  SDKUserMessageEvent,
  SendOptions,
  SettingSource,
  TextBlock,
  TokenUsage,
  ToolUseBlock,
  UsageCost,
} from "@cursor/sdk";

export {
  AgentBusyError,
  AuthenticationError,
  ConfigurationError,
  CursorAgentError,
  CursorAgentPlatform,
  IntegrationNotConnectedError,
  NetworkError,
  RateLimitError,
  UnknownAgentError,
  UnsupportedRunOperationError,
  createAgentPlatform,
  createInMemoryRunEventNotifier,
  createLocalRunEventNotifier,
  createSdkMessageRunStreamEvent,
  decodeLocalRunStreamEvent,
  decodeSdkMessageRunStreamEvent,
  getTurnType,
  isTerminalLocalRunStreamEvent,
  localRunStreamEventToSdkMessage,
  startLocalRunEventNotifierServer,
} from "@cursor/sdk";
